import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark flex min-h-screen w-full flex-col">

      <body className={inter.className}>
        <header className=" sticky top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6">
          <NavBar />
        </header>

        {

          children

        }</body>
    </html>
  );
}
